### Get all GTR entries
GET http://127.0.0.1:8080/gtr_entry

### Get specific entry of certain test_accession_ver
GET http://127.0.0.1:8080/gtr_entry/GTR000004034.1

### Get entries of certain gene,
#this is case sensitive
GET http://127.0.0.1:8080/gtr_entry/genes/HTT


### Get specific entry of certain internal_id
GET http://127.0.0.1:8080/gtr_entry/internal_id/1

### Get entries of certain lab_test_id
GET http://127.0.0.1:8080/gtr_entry/lab_test_id/4006

### Get Genomic Study for specific entry using internal ID
GET http://127.0.0.1:8080/gtr_fhir/1

### GET SWAGGER endpoint
GET http://localhost:8080/swagger-ui/index.html

### GET Genomic Study by Disease
GET http://localhost:8080/gtr_fhir/disease/C0001079

### Disease-level Genomic Study three analyses
GET http://localhost:8080/gtr_fhir/disease/C4518821

### Disease-level Genomic Study NO analysis
GET http://localhost:8080/gtr_fhir/disease/C4025140

### Disease-level Genomic Study 966 analyses
GET http://localhost:8080/gtr_fhir/disease/C0001079

### Disease-level Genomic Study with Device elements
GET http://localhost:8080/gtr_fhir/disease/C1839731




