### Get all GTR entries
GET http://127.0.0.1:8080/gtr_entry

### Get specific entry of certain test_accession_ver
GET http://127.0.0.1:8080/gtr_entry/GTR000004034.1

### Get entries of certain gene,
#this is case sensitive
GET http://127.0.0.1:8080/gtr_entry/genes/HTT


### Get specific entry of certain internal_id
GET http://127.0.0.1:8080/gtr_entry/internal_id/1

### Get entries of certain lab_test_id
GET http://127.0.0.1:8080/gtr_entry/internal_id/4006


