CREATE TABLE IF NOT EXISTS GtrEntry (
--     id INTEGER AUTO_INCREMENT,  -- for H2
                                       id SERIAL PRIMARY KEY,
                                       test_accession_ver varchar(255),
                                       name_of_laboratory varchar(255),
                                       name_of_institution varchar(255),
                                       facility_state varchar(255),
                                       facility_postcode varchar(255),
                                       facility_country varchar(255),
                                       CLIA_number varchar(255),
                                       state_licenses varchar(255),
                                       state_license_numbers varchar(255),
                                       lab_test_id varchar(255),
                                       last_touch_date varchar(255),
                                       lab_test_name varchar(255),
                                       manufacturer_test_name varchar(255),
                                       test_development varchar(255),
                                       lab_unique_code varchar(255),
                                       condition_identifiers varchar(255),
                                       indication_types varchar(255),
                                       inheritances varchar(255),
                                       method_categories varchar(255),
                                       methods varchar(255),
                                       platforms varchar(255),
                                       genes varchar(255),
                                       drug_responses varchar(255),
                                       now_current varchar(255),
                                       test_currStat varchar(255),
                                       test_pubStat varchar(255),
                                       lab_currStat varchar(255),
                                       lab_pubStat varchar(255),
                                       test_create_date varchar(255),
                                       test_deletion_date varchar(255)
--     , primary key (id) -- for H2
);