CREATE TABLE IF NOT EXISTS Gtr_Entry (
--     id INTEGER AUTO_INCREMENT,  -- for H2
                                       id SERIAL PRIMARY KEY,
                                       test_accession_ver text,
                                       name_of_laboratory text,
                                       name_of_institution text,
                                       facility_state text,
                                       facility_postcode text,
                                       facility_country text,
                                       CLIA_number text,
                                       state_licenses text,
                                       state_license_numbers text,
                                       lab_test_id text,
                                       last_touch_date text,
                                       lab_test_name text,
                                       manufacturer_test_name text,
                                       test_development text,
                                       lab_unique_code text,
                                       condition_identifiers text,
                                       indication_types text,
                                       inheritances text,
                                       method_categories text,
                                       methods text,
                                       platforms text,
                                       genes text,
                                       drug_responses text,
                                       now_current text,
                                       test_curr_stat text,
                                       test_pub_stat text,
                                       lab_curr_stat text,
                                       lab_pub_stat text,
                                       test_create_date TIMESTAMP,
                                       test_deletion_date TIMESTAMP
--     , primary key (id) -- for H2
);